name: Docker Outside Docker Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # 1) Run the steps themselves inside the official Docker CLI container
    container:
      image: docker:dind
      options: --privileged

    # 2) Spin up a Docker-in-Docker daemon as a service
    services:
      docker:
        image: docker:stable-dind     # or pin to a specific version
        options: >-
          --privileged
          -v /github/workspace:/github/workspace
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro

    steps:
      - uses: actions/checkout@v4
      - name: Prepare test directory
        run: |
          mkdir -p mydir
          echo "Hello from the job container!" > mydir/hello.txt

      - name: Run container AND mount that job-container path
        run: |
          docker run --rm \
            -v /github/workspace/mydir:/data \
            busybox cat /data/hello.txt
