name: Docker Outside Docker Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.10
      options: --user root  # needed if you need to install deps

    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375

    env:
      DOCKER_HOST: tcp://docker:2375

    steps:
      - uses: actions/checkout@v3

      - name: Install pip deps
        run: |
          apt-get update && apt-get install -y python3-pip python3-venv
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt -r etc/dev_requirements.txt

      - name: Create mount dir
        run: mkdir -p tests/data/tmp/mgdata

      - name: Run tests (containers will be children of DinD)
        run: |
          . venv/bin/activate
          pytest tests/test_mongodb.py

