name: Docker Outside Docker Tests

on: [push, pull_request]

jobs:
  docker-outside-docker:
    runs-on: ubuntu-latest

    container:
      image: docker:dind
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          apk update && apk add --no-cache \
            python3 \
            py3-pip \
            python3-dev \
            build-base \
            g++ \
            musl-dev \
            unixodbc-dev \
            libffi-dev \
            openssl-dev

      - name: Create and activate virtualenv, install deps
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir -r etc/dev_requirements.txt

      - name: Run Pytest with Docker SDK
        run: pytest tests/test_mongodb.py

      - name: Run Pytest with Docker SDK
        run: pytest tests/test_mssql.py

      - name: Run Pytest with Docker SDK
        run: pytest tests/test_postgres.py

      - name: Run Pytest with Docker SDK
        run: pytest tests/test_mysql.py
