name: Docker-in-Docker Tests

on: [push, pull_request]

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    container:
      image: docker:24.0.5-dind
      options: --privileged  # Required for Docker daemon

    services:
      docker:
        image: docker:24.0.5-dind
        options: --privileged --shm-size=2g

    steps:
      - name: Install dependencies
        run: |
          apk add --no-cache \
            python3 \
            py3-pip \
            py3-virtualenv \
            git \
            g++ \
            python3-dev \
            libffi-dev \
            openssl-dev \
            unixodbc-dev \
            build-base \
            curl

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up virtualenv
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt -r etc/dev_requirements.txt

      - name: Prepare mount dir
        run: mkdir -p /data/tmp/mgdata

      - name: Start Docker daemon
        run: |
          dockerd-entrypoint.sh &

          # Wait for daemon to be ready
          timeout 30 sh -c 'until docker info; do sleep 1; done'

      - name: Run Pytest (Docker SDK)
        run: |
          . venv/bin/activate
          pytest tests/test_mongodb.py
