name: Docker Outside Docker Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # 1) Run the steps themselves inside the official Docker CLI container
    container:
      image: docker:dind
      options: --privileged

    # 2) Spin up a Docker-in-Docker daemon as a service
    services:
      docker:
        image: docker:stable-dind     # or pin to a specific version
        options: >-
          --privileged
          -v /github/workspace:/workspace
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test file in the job container
        run: |
          mkdir -p mydir
          echo "Hello from the job container!" > mydir/hello.txt

      - name: Verify mount from DinD
        run: |
          # mount from the dind container’s /workspace 
          # into our new busybox container’s /data
          docker run --rm \
            -v /workspace/mydir:/data \
            busybox cat /data/hello.txt
